version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - gatsby-theme-cart-{{ checksum "package.json" }}
            - gatsby-theme-cart-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: gatsby-theme-cart-{{ checksum "package.json" }}
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - gatsby-theme-cart-{{ checksum "package.json" }}
      - run: yarn release

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          filters:
            branches:
              only: master
          requires:
            - build
